<?php

function ingredients () {
    return [
        "1 cup flour",
        "1 cup sugar",
        "1 cup milk",
        "1 cup water",
        "1 cup oil",
        "1 cup salt",
        "1 cup pepper",
        "1 cup butter",
        "1 cup eggs",
        "1 cup cheese",
        "1 cup bacon",
        "1 cup chicken",
        "1 cup beef",
        "1 cup pork",
        "1 cup fish",
        "1 cup rice",
        "1 cup pasta",
        "1 cup bread",
        "1 cup potatoes",
        "1 cup carrots",
        "1 cup celery",
        "1 cup onions",
        "1 cup garlic",
        "1 cup tomatoes",
        "1 cup lettuce",
        "1 cup spinach",
        "1 cup broccoli",
        "1 cup cauliflower",
        "1 cup mushrooms",
    ];
}
